"
"  ██╗   ██╗██╗███╗   ███╗██████╗  ██████╗
"  ██║   ██║██║████╗ ████║██╔══██╗██╔════╝
"  ██║   ██║██║██╔████╔██║██████╔╝██║
"  ╚██╗ ██╔╝██║██║╚██╔╝██║██╔══██╗██║
"   ╚████╔╝ ██║██║ ╚═╝ ██║██║  ██║╚██████╗
"     ╚═══╝  ╚═╝╚═╝     ╚═╝╚═╝  ╚═╝ ╚═════╝
"

if empty(glob('~/.config/vim/autoload/plug.vim'))
  silent !curl -fLo ~/.config/vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

source ~/.config/vim/plugins.vim

let mapleader=" "

" ================ THEME ========================

" Colorscheme configuration.
if &t_Co > 2
	syntax on
    set background=dark
     if &diff
          colorscheme github
     else
        colorscheme gruvbox
     endif

	highlight Folded cterm=reverse ctermbg=0 ctermfg=8
	highlight VertSplit cterm=NONE ctermbg=NONE ctermfg=8
	highlight Conceal cterm=NONE ctermbg=NONE ctermfg=8

	"highlight DiffAdd ctermfg=green cterm=bold
	"highlight DiffDelete ctermfg=red cterm=bold
	"highlight DiffChange ctermfg=yellow

	set colorcolumn=80

	" Sometimes I see the syntax be out of sync
	noremap <F12> <Esc>:syntax sync fromstart<CR>
	inoremap <F12> <C-o>:syntax sync fromstart<CR>
endif
hi Normal guibg=NONE ctermbg=NONE

" ================ General Config ====================
set clipboard=unnamedplus

""Mostrar los caracteres nulos
exec "set listchars=tab:\uBB\uBB,trail:\uB7,nbsp:~"
" Use a specific pipe ch
set fillchars+=vert:\┊
set list

let mapleader=" "

" Persist undo history between file editing sessions.
set undofile
set undodir=~/.vim/undodir

set number                          "Line numbers are good
set relativenumber
set cursorline                      "Highlight the line the cursor is on
set backspace=indent,eol,start      "Allow backspace in insert mode
set nocompatible                    "disable vi compatibility mode
set history=1000                    "Store lots of :cmdline history
set showcmd                         "Show incomplete cmds down the bottom
set gcr=a:blinkon0                  "Disable cursor blink
set visualbell                      "No sounds
set autoread                        "Reload files changed outside vim
set laststatus=2                    "Enabling statusline at all times
if &encoding != 'utf-8'
    set encoding=utf-8              "Necessary to show Unicode glyphs
endif
set spelllang=es,en
set noshowmode                      "Don't show the mode(airline is handling this)
set mouse=a                         "Mouse in terminal
set clipboard+=unnamedplus          "use system clipboard by default
set diffopt+=vertical               "prefer vertical diffs

set tw=79   " width of document (used by gd)
set fo-=t   " don't automatically wrap text when typing
set colorcolumn=80
""" numero de lineas visuales por TAB
set tabstop=4
set softtabstop=4
set shiftwidth=4
set shiftround
set expandtab
"" Autocomplete comandos
set wildmenu
"
"" Mostrar donde empieza y terminan brackets, etc
set showmatch
"
""buscar mientras escribo y resaltar
set incsearch
set ignorecase
set smartcase
"set gdefault

" Sane splits
set splitright
set splitbelow

" Wrapping options
set formatoptions=tc " wrap text and comments using textwidth
set formatoptions+=r " continue comments when pressing ENTER in I mode
set formatoptions+=q " enable formatting of comments with gq
set formatoptions+=n " detect lists for formatting
set formatoptions+=b " auto-wrap in insert mode, and do not wrap old long lines

""Molestos backup? para /tmp amiguitos
set nobackup
set nowritebackup
set noswapfile

" ================ Scrolling ========================

set scrolloff=8         "Start scrolling when we're 8 lines away from margins
set sidescrolloff=15
set sidescroll=1

highlight ColorColumn ctermbg=233

" ================ Indentation ======================

set autoindent
set smartindent
set smarttab

filetype indent plugin on

" Display tabs and trailing spaces visually
" set list listchars=trail:·,tab:┊\ ,extends:>,precedes:<,nbsp:·

set nowrap       "Don't wrap lines
set linebreak    "Wrap lines at convenient points


" ================ Folds ============================

set foldmethod=indent   "fold based on indent
set foldnestmax=3       "deepest fold is 3 levels
set nofoldenable        "dont fold by default    

let javaScript_fold=1         " JavaScript
let perl_fold=1               " Perl
let php_folding=1             " PHP
let r_syntax_folding=1        " R
let ruby_fold=1               " Ruby
let sh_fold_enabled=1         " sh
let vimsyn_folding='af'       " Vim script
let xml_syntax_folding=1      " XML

" fuck this madnesss
nnoremap k gk
nnoremap j gj
cmap Q! q!

"hide chars
map <leader>h :set list!<CR>
"" leader+space deja de mostrar el resultado de la busqueda
"nnoremap <leader><space> :nohlsearch<CR>

" I can type :help on my own, thanks.
map <F1> <Esc>
imap <F1> <Esc>

"toggle buffers
nnoremap <leader><leader> <c-^>

" Search results centered please
nnoremap <silent> n nzz
nnoremap <silent> N Nzz
nnoremap <silent> * *zz
nnoremap <silent> # #zz
nnoremap <silent> g* g*zz

"search magic
nnoremap ? ?\v
nnoremap / /\v
cnoremap %s/ %sm/

" easier moving of code blocks
" Try to go into visual mode (v), thenselect several lines of code here and
" then press ``>`` several times.
vnoremap < <gv  " better indentation
vnoremap > >gv  " better indentation
" Save rapidito
noremap <silent> <C-S>          :w<CR>
vnoremap <silent> <C-S>         <C-C>:w<CR>
inoremap <silent> <C-S>         <C-O>:w<CR>
""


" Jump to last edit position on opening file
if has("autocmd")
  " https://stackoverflow.com/questions/31449496/vim-ignore-specifc-file-in-autocommand
  au BufReadPost * if expand('%:p') !~# '\m/\.git/' && line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

"==========
"  FZF
"==========
let g:fzf_colors =
  \ { 'fg':      ['fg', 'Normal'],
  \ 'bg':      ['bg', 'Normal'],
  \ 'hl':      ['fg', 'Comment'],
  \ 'fg+':     ['fg', 'CursorLine', 'CursorColumn', 'Normal'],
  \ 'bg+':     ['bg', 'CursorLine', 'CursorColumn'],
  \ 'hl+':     ['fg', 'Statement'],
  \ 'info':    ['fg', 'PreProc'],
  \ 'prompt':  ['fg', 'Conditional'],
  \ 'pointer': ['fg', 'Exception'],
  \ 'marker':  ['fg', 'Keyword'],
  \ 'spinner': ['fg', 'Label'],
  \ 'header':  ['fg', 'Comment'] }

"" This is the default extra key bindings
let g:fzf_action = {
  \ 'ctrl-t': 'tab split',
  \ 'ctrl-x': 'split',
  \ 'ctrl-v': 'vsplit' }

"" In Neovim, you can set up fzf window using a Vim command
let g:fzf_layout = { 'down': '40%' }

nnoremap <leader>p :History<CR>
nnoremap <leader>t :Files<CR>
nmap ; :Buffers<CR>


" Marker concealment
if has('conceal')
  set conceallevel=2 concealcursor=niv
endif

"    =============== 
"         NERD
"    =============== 
let g:NERDTreeMinimalUI = 1
let g:NERDTreeMarkBookmarks = 0
let g:NERDTreeAutoDeleteBuffer = 1
let g:NERDTreeStatusLine = -1
nnoremap <silent> <Leader>n :NERDTreeToggle<CR>

"    =============== 
"         WIKI
"    =============== 
let g:vimwiki_list = [{'path': '$XDG_CONFIG_HOME/vimwiki',
		  \ 'path_html': '$XDG_CONFIG_HOME/vimwiki/wiki_html/',
		  \ 'template_path': '$XDG_CONFIG_HOME/vimwiki/templates',
		  \ 'template_default': 'def_template',
		  \ 'auto_toc': 1,
		  \ 'template_ext': '.html'}]
let g:vimwiki_valid_html_tags = 'b,i,s,u,sub,sup,kbd,br,hr, pre, script'
autocmd FileType vimwiki inoremap <F5> <Esc>:VimwikiAll2HTML<Enter>
autocmd FileType vimwiki nnoremap <F5> :VimwikiAll2HTML<Enter>


"    =============== 
"         TEX
"    =============== 
autocmd FileType tex inoremap <F5> <Esc>:VimtexCompile<Enter>a
autocmd FileType tex nnoremap <F5> :VimtexCompile<Enter>

vnoremap <leader>en :!python2 -c 'import sys,urllib;print urllib.quote(sys.stdin.read().strip())'<cr>
vnoremap <leader>de :!python2 -c 'import sys,urllib;print urllib.unquote(sys.stdin.read().strip())'<cr>

let g:coc_global_extensions = [
  \ 'coc-snippets',
  \ 'coc-pairs',
  \ 'coc-tsserver',
  \ 'coc-prettier', 
  \ 'coc-json', 
  \ ]

map dp :diffput<CR>
map dg :diffget<CR>

let g:tex_flavor = "latex"
